#声明微服模块的端口号
server:
  port: 9001

#声明微服务的名称(微服务的service-id)
spring:
  application:
    name: microservice-user
  #声明微服务访问数据库的4大参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.41.49:3306/jsd21131?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
  #声明微服务使用jpa正向工程
  jpa:
    database: mysql
    generate-ddl: true #声明产生建表语句
    show-sql: true #生成的sql语句在控制台中显示

#用户微服务向Eureka服务器注册
eureka:
  client:
    #是否向Eureka服务器注册? 是
    register-with-eureka: true
    #是否向Eureka服务器索要信息?是
    fetch-registry: true
    #向Eureka服务器发出注册请求
    service-url: #service指的是Eureka服务
      defaultZone: http://192.168.41.1:8888/eureka

  #微服务管理
  #微服务的提供方与Eureka服务器的约定
  instance:
    #心跳(发送心跳的时间间隔)
    lease-renewal-interval-in-seconds: 10 #默认30秒
    #设置微服务失效的标准
    lease-expiration-duration-in-seconds: 30 #默认90秒